routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Basic Routes
Route::get('/', function () {
    return view('welcome');
});

// Auth Routes
Route::get('/login', function () {
    return view('login');
});

Route::post('/2fa', function () {
    return redirect(URL()->previous());
})->name('2fa')->middleware('2fa');

Route::get('/register/invite', function () { return view('auth.invite'); })->name('register/invite');
Route::post('/register/invite', 'Auth\RegisterController@checkInvite')->name('register/invite2');
Route::get('/register/2fa', 'Auth\RegisterController@enable2fa')->name('register/2fa');
Route::get('/register/complete', 'Auth\RegisterController@completeRegistration')->name('register/complete');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Auth::routes();

// Account Routes
Route::get(
	'account/activate/{token}', 
	'Auth\ActivationController@activate'
)->name('account.activate_acc');

Route::get(
    'account/activation/request',
    'Auth\ActivationController@request'
)->name('account.activation.request');

Route::post(
    'account/resend/activation',
    'Auth\ActivationController@resend'
)->name('account.activation.resend');

Route::get('/2fa/enable', 'UserController@enableTwoFactor');
Route::get('/2fa/disable', 'UserController@disableTwoFactor');

// Utilities Route
Route::get('/phpinfo', function () {
    phpinfo();
});

// Resource Routes
Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');
Route::resource('companies', 'CompanyController');

// Application Routes
Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth', '2fa']);

// Admin Routes
Route::get('/admin/index', function(){ return view('admin.index'); })->middleware(['auth', 'isAdmin']);
Route::get('/admin/companies', 'CompanyController@index')->name('admin/company')->middleware(['auth', 'isAdmin']);

resources/views/admin/companies-create.blade.php
@extends('layouts.app')

@section('title', '| Create Permission')

@section('content')

<div class='col-lg-4 col-lg-offset-4'>

    <h1><i class='fa fa-key'></i> Add Company</h1>
    <br>

    {{ Form::open(array('url' => 'companies')) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        <label for="address">Address</label>
        <textarea name="address"></textarea>
    </div>
    <div class="form-group">
        {{ Form::label('telnum', 'Telephone') }}
        {{ Form::text('telnum', '', array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('faxnum', 'Fax') }}
        {{ Form::text('faxnum', '', array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('website', 'Website') }}
        {{ Form::text('website', '', array('class' => 'form-control')) }}
    </div>
    <div class='form-group'>
        <p>Role</p>
        @foreach ($roles as $role)
            {{ Form::checkbox('roles[]',  $role->id ) }}
            {{ Form::label($role->name, ucfirst($role->name)) }}<br>

        @endforeach
    </div>
    <div class="form-group">
        <p>Invite Code</p>
        @foreach ($invites as $invite)
            {{ Form::checkbox('invites[]',  $invite->code ) }}
            {{ Form::label($invite->code, ucfirst($invite->code)) }}<br>

        @endforeach
    </div>
    <br>
    <br>
    {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

    {{ Form::close() }}

</div>

@endsection

resources/views/admin/companies.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
<div class="col-lg-10 col-lg-offset-1">
    <h1><i class="fa fa-users"></i> User Administration</h1>
    <hr>
    <div class="table-responsive">
        <table class="table table-bordered table-striped">

            <thead>
                <tr>
                    <th>Name</th>
                    <th>Invite Code</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($companies as $user)
                <tr>

                    <td>{{ $user->company_name }}</td>
                    <td>{{ $user->invite_code }}</td>
                    <td>
                    <a href="{{ route('companies.edit', $user->id) }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                    {!! Form::open(['method' => 'DELETE', 'route' => ['companies.destroy', $user->id] ]) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                    {!! Form::close() !!}

                    </td>
                </tr>
                @endforeach
            </tbody>

        </table>
    </div>

    <a href="{{ route('companies.create') }}" class="btn btn-success">Add User</a>

</div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('title', 'Administration')

@section('content')
<div class="container-fluid">
	<ul class="nav nav-tabs" id="myTab" role="tablist">
	  <li class="nav-item">
	    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Home</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab" aria-controls="messages" aria-selected="false">Messages</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false">Settings</a>
	  </li>
	</ul>

	<div class="tab-content">
	  <div class="tab-pane active" id="home" role="tabpanel" aria-labelledby="home-tab">
	  </div>
	  <div class="tab-pane" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
	  <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">...</div>
	  <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">...</div>
	</div>
</div>
@endsection